name: share_card_open
description: "A new Flutter project."
publish_to: 'none'
version: 0.1.0

environment:
  sdk: '>=3.4.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  http: ^0.13.4
  flutter_colorpicker: ^1.0.3
  share: ^2.0.4
  path_provider: ^2.1.3
  social_share: ^2.3.1
  appinio_social_share: ^0.3.1
  file_picker: ^8.0.4
  
  

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^3.0.0


flutter:
  uses-material-design: true
  assets: 
    - assets/
